[phases.setup]
nixPkgs = ["nodejs-18_x", "ffmpeg"]

[phases.install]
cmds = ["cd backend && npm ci"]

[phases.build]
cmds = ["cd backend && npm run build"]

[start]
cmd = "cd backend && node dist/index.js"